### ISSUE TITLE
Warnings/errors when clicking on blank spot in figure

### ISSUE THREAD

**Issue by henrikjacobsenfys** [Jakob-Lass/MJOLNIR#39]
When plotting data in as function of (Q,E), clicking on a point on the colormap prints a bunch of useful information, such as:
h = 1.986, h = 1.986, l = 0.000, E = 1.750, I = 3.494e-07, Cts = 2, Norm = 3448.000, Mon = 3800000, NormCount = 38

However, when clicking on a spot with no data the useful information is replaced by a bunch of errors or warnings:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\matplotlib\cbook\__init__.py", line 216, in process
    func(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\MJOLNIR\Data\DataSet.py", line 1971, in <lambda>
    ax._button_press_event = ax.figure.canvas.mpl_connect('button_press_event',lambda event:onclick(event,ax,DataList))
  File "c:\program files\python37\lib\site-packages\MJOLNIR\Data\DataSet.py", line 1962, in onclick
    dataPoint = DataList[np.logical_and(DataList['qCut']==segID,DataList['energyCut']==Eindex)].iloc[index]
  File "c:\program files\python37\lib\site-packages\pandas\core\indexing.py", line 1424, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "c:\program files\python37\lib\site-packages\pandas\core\indexing.py", line 2157, in _getitem_axis
    self._validate_integer(key, axis)
  File "c:\program files\python37\lib\site-packages\pandas\core\indexing.py", line 2088, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\matplotlib\cbook\__init__.py", line 216, in process
    func(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\matplotlib\backend_bases.py", line 2713, in mouse_move
    s = event.inaxes.format_coord(event.xdata, event.ydata)
  File "c:\program files\python37\lib\site-packages\MJOLNIR\Data\DataSet.py", line 1970, in <lambda>
    ax.format_coord = lambda x,y: format_coord(x,y,edgeQDistance,centerPositionTotal,actualEnergy,DataList,rlu,offset,self)#EnergyBins
  File "c:\program files\python37\lib\site-packages\MJOLNIR\Data\DataSet.py", line 1904, in format_coord
    Intensity = DataList['Int'][np.logical_and(DataList['qCut']==segID,DataList['energyCut']==Eindex)].iloc[index]  #Int[segID][Eindex][index][0]
  File "c:\program files\python37\lib\site-packages\pandas\core\indexing.py", line 1424, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "c:\program files\python37\lib\site-packages\pandas\core\indexing.py", line 2157, in _getitem_axis
    self._validate_integer(key, axis)
  File "c:\program files\python37\lib\site-packages\pandas\core\indexing.py", line 2088, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

**Comment by Jakob-Lass** [comment]
Thank you for this issue, which in general is really annoying. It has been changed in update 7fac37e44e6534c5b425997ddeb637bdb1225e9c to look for out of range indices and negative indices such that the above described problem is removed.
